In [1]:
# Free RAM
!free -h

               total        used        free      shared  buff/cache   available
Mem:            15Gi       6.7Gi       4.7Gi       180Mi       5.3Gi       8.8Gi
Swap:           19Gi          0B        19Gi


In [2]:
# Free CPU
!lscpu

Architecture:                x86_64
  CPU op-mode(s):            32-bit, 64-bit
  Address sizes:             43 bits physical, 48 bits virtual
  Byte Order:                Little Endian
CPU(s):                      12
  On-line CPU(s) list:       0-11
Vendor ID:                   AuthenticAMD
  Model name:                AMD Ryzen 5 2600 Six-Core Processor
    CPU family:              23
    Model:                   8
    Thread(s) per core:      2
    Core(s) per socket:      6
    Socket(s):               1
    Stepping:                2
    Frequency boost:         enabled
    CPU(s) scaling MHz:      72%
    CPU max MHz:             3400.0000
    CPU min MHz:             1550.0000
    BogoMIPS:                6786.33
    Flags:                   fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pg
                             e mca cmov pat pse36 clflush mmx fxsr sse sse2 ht s
                             yscall nx mmxext fxsr_opt pdpe1gb rdtscp lm constan
                          

In [3]:
# Disk
!df -h

Filesystem      Size  Used Avail Use% Mounted on
tmpfs           1.6G  1.9M  1.6G   1% /run
efivarfs        128K  9.4K  114K   8% /sys/firmware/efi/efivars
/dev/sdb3       211G   48G  153G  24% /
tmpfs           7.8G   13M  7.8G   1% /dev/shm
tmpfs           5.0M     0  5.0M   0% /run/lock
/dev/sdb2       4.0G  3.4G  665M  84% /recovery
/dev/sdb1      1020M  438M  583M  43% /boot/efi
/dev/sda2       932G  312G  621G  34% /mnt/HD1
/dev/sdc2       932G  351G  581G  38% /mnt/HD2
tmpfs           1.6G  2.6M  1.6G   1% /run/user/1000


In [4]:
# GPU
!nvidia-smi

Wed Jun 10 16:34:59 2026       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 580.159.03             Driver Version: 580.159.03     CUDA Version: 13.0     |
+-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA GeForce GTX 1660 Ti     Off |   00000000:07:00.0  On |                  N/A |
|  0%   48C    P8              6W /  120W |     932MiB /   6144MiB |      6%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

In [5]:
import pandas as pd

In [6]:
url = "https://raw.githubusercontent.com/alexeygrigorev/datasets/master/housing.csv"

df = pd.read_csv(url)

In [7]:
df.head()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,ocean_proximity
0,-122.23,37.88,41.0,880.0,129.0,322.0,126.0,8.3252,452600.0,NEAR BAY
1,-122.22,37.86,21.0,7099.0,1106.0,2401.0,1138.0,8.3014,358500.0,NEAR BAY
2,-122.24,37.85,52.0,1467.0,190.0,496.0,177.0,7.2574,352100.0,NEAR BAY
3,-122.25,37.85,52.0,1274.0,235.0,558.0,219.0,5.6431,341300.0,NEAR BAY
4,-122.25,37.85,52.0,1627.0,280.0,565.0,259.0,3.8462,342200.0,NEAR BAY


# **Introduction to NumPy**
- Create arrays
- Multi-dimensional arrays
- Random arrays
- Element-wise operations
- Summarizing operations

In [8]:
import numpy as np

In [9]:
np

<module 'numpy' from '/mnt/HD2/Data_Science/ml-engineering-zoomcamp/.venv/lib/python3.12/site-packages/numpy/__init__.py'>

## Creating Arrays

In [10]:
# Creates an array of zeros.
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [11]:
# Creates an array of ones
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [ ]:
# Creates an array filled with arbitrary numbers
np.full(10, 2.5)  # size and element we want to fill with.

array([2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5])

In [13]:
# Convert a list into an array
a = np.array([1, 2, 3, 4, 5])

In [14]:
a

array([1, 2, 3, 4, 5])

In [ ]:
a[2]  # Accessing an element

np.int64(3)

In [16]:
# Changing an element of the array
a[2] = 200

In [17]:
a

array([  1,   2, 200,   4,   5])

In [ ]:
# Creates an array from a specific range
np.arange(10)  # Array from zero to nine

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.arange(3, 10)  # Array from 3 to 9

array([3, 4, 5, 6, 7, 8, 9])

In [ ]:
# Creates an array filled with number between the values specified in the arguments
np.linspace(0, 1)  # By default, creates an array of size 50.

array([0.        , 0.02040816, 0.04081633, 0.06122449, 0.08163265,
       0.10204082, 0.12244898, 0.14285714, 0.16326531, 0.18367347,
       0.20408163, 0.2244898 , 0.24489796, 0.26530612, 0.28571429,
       0.30612245, 0.32653061, 0.34693878, 0.36734694, 0.3877551 ,
       0.40816327, 0.42857143, 0.44897959, 0.46938776, 0.48979592,
       0.51020408, 0.53061224, 0.55102041, 0.57142857, 0.59183673,
       0.6122449 , 0.63265306, 0.65306122, 0.67346939, 0.69387755,
       0.71428571, 0.73469388, 0.75510204, 0.7755102 , 0.79591837,
       0.81632653, 0.83673469, 0.85714286, 0.87755102, 0.89795918,
       0.91836735, 0.93877551, 0.95918367, 0.97959184, 1.        ])

In [21]:
np.linspace(0, 1, 10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

## Multi-dimensional arrays

In [ ]:
np.zeros((5, 2))  # Rows, columns

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [ ]:
n = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [ ]:
n[0]  # access the first row

array([1, 2, 3])

In [ ]:
n[0][1]  # access first row, second column.

np.int64(2)

In [26]:
# Similarly
n[0, 1]

np.int64(2)

In [27]:
# Re-writing the entire row
n[2] = [0, 0, 0]

In [28]:
n

array([[1, 2, 3],
       [4, 5, 6],
       [0, 0, 0]])

In [ ]:
# Access only the column
n[:, 1]

array([2, 5, 0])

## Random arrays

In [ ]:
# Generates a random array with 5 rows and 2 columns that follows a uniform distribution ranging from 0 to 1.
a = np.random.rand(5, 2)
a

array([[0.65037651, 0.68381489],
       [0.71378838, 0.54668316],
       [0.24995407, 0.71132571],
       [0.68121625, 0.61437993],
       [0.38249018, 0.39515689]])

In [ ]:
# Generates a random array from the standard normal distribution
b = np.random.randn(5, 2)
b

array([[ 0.38006382, -1.75751292],
       [ 0.04150426, -0.47767187],
       [ 0.61002154,  0.87529171],
       [-0.38913079, -0.17020993],
       [-0.95072422, -0.06431992]])

In [32]:
# Generates a random array with integer values
c = np.random.randint(low=0, high=100, size=[10, 3])
c

array([[35, 21, 70],
       [ 6, 36,  6],
       [61, 70, 64],
       [81, 71, 68],
       [58, 85, 25],
       [36, 14, 66],
       [ 1, 63, 77],
       [63, 41, 92],
       [ 1,  6, 55],
       [93, 20, 63]])

## Element-wise operations

In [33]:
n = np.arange(5)
n

array([0, 1, 2, 3, 4])

In [34]:
# Add the value of the scalar to each element inside the array
n + 1

array([1, 2, 3, 4, 5])

In [35]:
# Multiply all the entries by a scalar
n * 2

array([0, 2, 4, 6, 8])

In [36]:
n / 100

array([0.  , 0.01, 0.02, 0.03, 0.04])

In [37]:
# Chain of operations
(10 + (n * 2)) ** 2 / 100

array([1.  , 1.44, 1.96, 2.56, 3.24])

In [38]:
b = (10 + (n * 2)) ** 2 / 100

In [39]:
# Combine two arrays
c = n + b
c

array([1.  , 2.44, 3.96, 5.56, 7.24])

## Comparison Operations

In [40]:
# Element-wise comparison
n >= 2

array([False, False,  True,  True,  True])

In [41]:
n > b

array([False, False,  True,  True,  True])

In [42]:
n

array([0, 1, 2, 3, 4])

In [43]:
b

array([1.  , 1.44, 1.96, 2.56, 3.24])

In [ ]:
# Analyse which element of an array is greater then the other array
n[n > b]  # Returns the elements of A that has truthiness

array([2, 3, 4])

## Summarizing operations
Instead of return another array, it returns a single number

In [45]:
a

array([[0.65037651, 0.68381489],
       [0.71378838, 0.54668316],
       [0.24995407, 0.71132571],
       [0.68121625, 0.61437993],
       [0.38249018, 0.39515689]])

In [46]:
a.sum()

np.float64(5.629185951481279)

In [47]:
a.mean()

np.float64(0.5629185951481279)

In [48]:
a.max()

np.float64(0.7137883761656872)

In [49]:
a.min()

np.float64(0.24995406739862658)

In [ ]:
np.mean(a, axis=0)  # Mean of each column

array([0.53556508, 0.59027212])

In [ ]:
np.mean(a, axis=1)  # Mean of each row

array([0.6670957 , 0.63023577, 0.48063989, 0.64779809, 0.38882353])

# **Linear Algebra Refresher**
- Vector Operations
- Multiplication
- Matrix Inverse

## Vector Operations

In [52]:
a = np.array([2, 4, 5, 6])
a

array([2, 4, 5, 6])

In [53]:
2 * a

array([ 4,  8, 10, 12])

In this operation above, we are just multiplying the vector "a" by a scalar of 2. In Linear Algebra, this mean to multiply each entry of the vector by this scalar.

In [54]:
b = np.array([1, 0, 0, 2])

In [55]:
a + b

array([3, 4, 5, 8])

In the operation above, we are adding the vector "a" with the vector "b". It just mean that we area adding element-wise the vector values of "a" with the vector values of "b".

## Multiplication
- Vector-vector multiplication (**dot product**)
- Matrix-vector multiplication
- Matrix-matrix multiplication

In [56]:
a

array([2, 4, 5, 6])

In [57]:
b

array([1, 0, 0, 2])

The dot product is not just a element-wise multiplication. It is a element-wise multiplication followed by a sum. The result generates a single number.

In [58]:
# Implementation of a function that calculates the dot product
def dot_product(u: np.array, v: np.array) -> int:
    assert u.shape[0] == v.shape[0]
    n = u.shape[0]
    result = 0.0
    for i in range(n):
        result = result + u[i] * v[i]

    return result

In [59]:
dot_product(a, b)

np.float64(14.0)

In [60]:
# NumPy has a implemented function that does this calculation
a.dot(b)

np.int64(14)

We can also multiply a Matrix by a Vector. We do this by taking the first row of the matrix U and multiply by the vector V, and so on. For this operation to work, we need to make sure that the number of columns in the matrix U is the same as the number of rows in the vector V.

In [ ]:
U = np.array([[2, 4, 5, 6], [1, 2, 1, 2], [3, 1, 2, 1]])

In [62]:
U

array([[2, 4, 5, 6],
       [1, 2, 1, 2],
       [3, 1, 2, 1]])

In [70]:
# Defining the Matrix Vector multiplication with just Python
def matrix_vector_multiplication(U: np.array, V: np.array) -> np.array:
    assert U.shape[1] == V.shape[0]

    n_rows = U.shape[0]
    result_vector = np.array([dot_product(U[i], V) for i in range(n_rows)])
    return result_vector

In [65]:
U.shape

(3, 4)

In [72]:
V

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [ ]:
V = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])

In [101]:
w = matrix_vector_multiplication(U, V)

In [88]:
V.shape

(4, 1)

In [102]:
w

array([[113., 130., 147.],
       [ 36.,  42.,  48.],
       [ 31.,  38.,  45.]])

In [84]:
w.shape

(3, 3)

In [89]:
u = U.dot(V)

In [90]:
u

array([[49],
       [16],
       [15]])

For a matrix-matrix multiplication, we have 2 matrices, U and V, and the result is a new matrix with the number of rows in U and the number of columns of V. We can only multiply two matrices if the number of columns in the first matrix is equal to the number of rows in the second matrix. In short, if we multiply a matrix A (m x n) by a matrix B (n x p), the resulting matrix Z will be m x p.

In [ ]:
# Implementing matrix-matrix multiplication in Python
def matrix_matrix_multiplication(A: np.array, B: np.array) -> np.array:
    assert A.shape[1] == B.shape[0]

    n_rows = A.shape[0]
    n_cols = B.shape[1]

    result = np.zeros((n_rows, n_cols))
    for i in range(n_cols):
        bi = B[:, i]  # Col i of matrix B
        Ubi = matrix_vector_multiplication(A, bi)
        result[:, i] = Ubi
    return result

In [ ]:
# We can also simplify this function with following code:
def simplified_matrix_matrix_multiplication(A: np.array, B: np.array) -> np.array:
    assert A.shape[1] == B.shape[0]

    return A @ B  # or np.dot(A, B)

The __Identity matrix__ is a square matrix where the diagonal is filled with 1 and filled with 0 in every other position.

In [97]:
# identity matrix in numpy
I = np.eye(4)
I

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [104]:
U.dot(I)

array([[2., 4., 5., 6.],
       [1., 2., 1., 2.],
       [3., 1., 2., 1.]])

The __Inverse Matrix__ is a matrix that, when multiplied by its original matrix A, results in the identity matrix. In other words: A * A^-1 = A^-1 * A = I

Important: only square matrices has a inverse matrix.

In [ ]:
A = np.array([[4, 2, 3], [4, 5, 6], [7, 8, 9]])

In [121]:
inverse = np.linalg.inv(A)
inverse

array([[ 0.33333333, -0.66666667,  0.33333333],
       [-0.66666667, -1.66666667,  1.33333333],
       [ 0.33333333,  2.        , -1.33333333]])

In [122]:
inverse.dot(A)

array([[ 1.00000000e+00,  1.33226763e-15,  1.94289029e-15],
       [-1.11022302e-15,  1.00000000e+00, -6.66133815e-16],
       [-4.44089210e-16,  0.00000000e+00,  1.00000000e+00]])

# **Introduction to Pandas**
- DataFrames
- Series
- Index
- Accessing Elements
- Element-wise operations
- Filtering
- String Operations
- Summaring Operations
- Missing Values
- Grouping
- Getting the NumPy arrays

In [1]:
import pandas as pd
import numpy as np

### DataFrames - is the main data structure in pandas

In [ ]:
data = [
    ["Nissan", "Stanza", 1991, 138, 4, "MANUAL", "sedan", 2000],
    ["Hyundai", "Sonata", 2017, None, 4, "AUTOMATIC", "Sedan", 27150],
    ["Lotus", "Elise", 2010, 218, 4, "MANUAL", "convertible", 54990],
    ["GMC", "Acadia", 2017, 194, 4, "AUTOMATIC", "4dr SUV", 34450],
    ["Nissan", "Frontier", 2017, 261, 6, "MANUAL", "Pickup", 32340],
]

columns = [
    "Make",
    "Model",
    "Year",
    "Engine HP",
    "Engine Cylinders",
    "Transmission Type",
    "Vehicle_Style",
    "MSRP",
]

df = pd.DataFrame(data, columns=columns)
df

,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Vehicle_Style,MSRP
0,Nissan,Stanza,1991,138.0,4,MANUAL,sedan,2000
1,Hyundai,Sonata,2017,NaN,4,AUTOMATIC,Sedan,27150
2,Lotus,Elise,2010,218.0,4,MANUAL,convertible,54990
3,GMC,Acadia,2017,194.0,4,AUTOMATIC,4dr SUV,34450
4,Nissan,Frontier,2017,261.0,6,MANUAL,Pickup,32340


In [ ]:
# Alternatively, we can use a list of dicts to create a dataframe:
# In this case, pandas will use the name of the keys in the dict to create the columns
data = [
    {
        "Make": "Nissan",
        "Model": "Stanza",
        "Year": 1991,
        "Engine HP": 138.0,
        "Engine Cylinders": 4,
        "Transmission Type": "MANUAL",
        "Vehicle_Style": "sedan",
        "MSRP": 2000,
    },
    {
        "Make": "Hyundai",
        "Model": "Sonata",
        "Year": 2017,
        "Engine HP": None,
        "Engine Cylinders": 4,
        "Transmission Type": "AUTOMATIC",
        "Vehicle_Style": "Sedan",
        "MSRP": 27150,
    },
    {
        "Make": "Lotus",
        "Model": "Elise",
        "Year": 2010,
        "Engine HP": 218.0,
        "Engine Cylinders": 4,
        "Transmission Type": "MANUAL",
        "Vehicle_Style": "convertible",
        "MSRP": 54990,
    },
    {
        "Make": "GMC",
        "Model": "Acadia",
        "Year": 2017,
        "Engine HP": 194.0,
        "Engine Cylinders": 4,
        "Transmission Type": "AUTOMATIC",
        "Vehicle_Style": "4dr SUV",
        "MSRP": 34450,
    },
    {
        "Make": "Nissan",
        "Model": "Frontier",
        "Year": 2017,
        "Engine HP": 261.0,
        "Engine Cylinders": 6,
        "Transmission Type": "MANUAL",
        "Vehicle_Style": "Pickup",
        "MSRP": 32340,
    },
]

In [4]:
df = pd.DataFrame(data)
df

,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Vehicle_Style,MSRP
0,Nissan,Stanza,1991,138.0,4,MANUAL,sedan,2000
1,Hyundai,Sonata,2017,NaN,4,AUTOMATIC,Sedan,27150
2,Lotus,Elise,2010,218.0,4,MANUAL,convertible,54990
3,GMC,Acadia,2017,194.0,4,AUTOMATIC,4dr SUV,34450
4,Nissan,Frontier,2017,261.0,6,MANUAL,Pickup,32340


In [ ]:
df.head()  # Show first n rows

,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Vehicle_Style,MSRP
0,Nissan,Stanza,1991,138.0,4,MANUAL,sedan,2000
1,Hyundai,Sonata,2017,NaN,4,AUTOMATIC,Sedan,27150
2,Lotus,Elise,2010,218.0,4,MANUAL,convertible,54990
3,GMC,Acadia,2017,194.0,4,AUTOMATIC,4dr SUV,34450
4,Nissan,Frontier,2017,261.0,6,MANUAL,Pickup,32340


In [ ]:
df.shape  # Show the shape/format of the DF

(5, 8)

### Series
Is a very importante concept in pandas. Each column in the dataframe is a pandas series. In pandas, a DataFrame is a table and a table consists of multiple pandas series, and each column is a pandas series.

In [ ]:
df.Make  # Accesing a specific column

0     Nissan
1    Hyundai
2      Lotus
3        GMC
4     Nissan
Name: Make, dtype: object

In [ ]:
df["Make"]  # Accesing a specific column

0     Nissan
1    Hyundai
2      Lotus
3        GMC
4     Nissan
Name: Make, dtype: object

In [ ]:
# Accessing multiple columns
df[["Make", "Model", "MSRP"]]

,Make,Model,MSRP
0,Nissan,Stanza,2000
1,Hyundai,Sonata,27150
2,Lotus,Elise,54990
3,GMC,Acadia,34450
4,Nissan,Frontier,32340


In [ ]:
# Adding a column to the dataframe
df["id"] = [1, 2, 3, 4, 5]

In [11]:
df

,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Vehicle_Style,MSRP,id
0,Nissan,Stanza,1991,138.0,4,MANUAL,sedan,2000,1
1,Hyundai,Sonata,2017,NaN,4,AUTOMATIC,Sedan,27150,2
2,Lotus,Elise,2010,218.0,4,MANUAL,convertible,54990,3
3,GMC,Acadia,2017,194.0,4,AUTOMATIC,4dr SUV,34450,4
4,Nissan,Frontier,2017,261.0,6,MANUAL,Pickup,32340,5


In [ ]:
# Deleting a column
del df["id"]

In [13]:
df

,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Vehicle_Style,MSRP
0,Nissan,Stanza,1991,138.0,4,MANUAL,sedan,2000
1,Hyundai,Sonata,2017,NaN,4,AUTOMATIC,Sedan,27150
2,Lotus,Elise,2010,218.0,4,MANUAL,convertible,54990
3,GMC,Acadia,2017,194.0,4,AUTOMATIC,4dr SUV,34450
4,Nissan,Frontier,2017,261.0,6,MANUAL,Pickup,32340


### Accessing Elements

In [14]:
df.index

RangeIndex(start=0, stop=5, step=1)

In [ ]:
# Accesing elements by its position
df.loc[1]  # uses labels (names) to select data

Make                   Hyundai
Model                   Sonata
Year                      2017
Engine HP                  NaN
Engine Cylinders             4
Transmission Type    AUTOMATIC
Vehicle_Style            Sedan
MSRP                     27150
Name: 1, dtype: object

In [ ]:
df.iloc[2]  # uses integer positions

Make                       Lotus
Model                      Elise
Year                        2010
Engine HP                  218.0
Engine Cylinders               4
Transmission Type         MANUAL
Vehicle_Style        convertible
MSRP                       54990
Name: 2, dtype: object

In [22]:
df.iloc[[2, 3, 4]]

,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Vehicle_Style,MSRP
2,Lotus,Elise,2010,218.0,4,MANUAL,convertible,54990
3,GMC,Acadia,2017,194.0,4,AUTOMATIC,4dr SUV,34450
4,Nissan,Frontier,2017,261.0,6,MANUAL,Pickup,32340


### Element-wise operations
Those calculations below are applied to every observation in the entire serie.

In [ ]:
df["Engine HP"] / 100

0    1.38
1     NaN
2    2.18
3    1.94
4    2.61
Name: Engine HP, dtype: float64

### Filtering
Allow us the retrieve some records based on specific filters.

In [ ]:
df["Year"] >= 2015

0    False
1     True
2    False
3     True
4     True
Name: Year, dtype: bool

In [ ]:
df[df["Year"] >= 2015]  # Single filter

,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Vehicle_Style,MSRP
1,Hyundai,Sonata,2017,NaN,4,AUTOMATIC,Sedan,27150
3,GMC,Acadia,2017,194.0,4,AUTOMATIC,4dr SUV,34450
4,Nissan,Frontier,2017,261.0,6,MANUAL,Pickup,32340


In [ ]:
df[(df["Make"] == "Nissan") & (df["Year"] >= 2015)]  # Multiple filter

,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Vehicle_Style,MSRP
4,Nissan,Frontier,2017,261.0,6,MANUAL,Pickup,32340


### String Operations

In [ ]:
df["Vehicle_Style"]

0          sedan
1          Sedan
2    convertible
3        4dr SUV
4         Pickup
Name: Vehicle_Style, dtype: object

In [ ]:
# First, we use the 'str' that allows to invoke string methods on the entire serie.
df["Vehicle_Style"].str.lower()

0          sedan
1          sedan
2    convertible
3        4dr suv
4         pickup
Name: Vehicle_Style, dtype: object

In [ ]:
df["Vehicle_Style"].str.lower().str.replace(" ", "_")

0          sedan
1          sedan
2    convertible
3        4dr_suv
4         pickup
Name: Vehicle_Style, dtype: object

In [ ]:
df["Vehicle_Style"] = df["Vehicle_Style"].str.lower().str.replace(" ", "_")

In [37]:
df

,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Vehicle_Style,MSRP
0,Nissan,Stanza,1991,138.0,4,MANUAL,sedan,2000
1,Hyundai,Sonata,2017,NaN,4,AUTOMATIC,sedan,27150
2,Lotus,Elise,2010,218.0,4,MANUAL,convertible,54990
3,GMC,Acadia,2017,194.0,4,AUTOMATIC,4dr_suv,34450
4,Nissan,Frontier,2017,261.0,6,MANUAL,pickup,32340


### Summarizing operations

In [ ]:
df["MSRP"].max()

np.int64(54990)

In [ ]:
df["MSRP"].min()

np.int64(2000)

In [ ]:
df["MSRP"].describe()

count        5.000000
mean     30186.000000
std      18985.044904
min       2000.000000
25%      27150.000000
50%      32340.000000
75%      34450.000000
max      54990.000000
Name: MSRP, dtype: float64

In [42]:
df.describe().round(2)

,Year,Engine HP,Engine Cylinders,MSRP
count,5.00,4.00,5.00,5.00
mean,2010.40,202.75,4.40,30186.00
std,11.26,51.30,0.89,18985.04
min,1991.00,138.00,4.00,2000.00
25%,2010.00,180.00,4.00,27150.00
50%,2017.00,206.00,4.00,32340.00
75%,2017.00,228.75,4.00,34450.00
max,2017.00,261.00,6.00,54990.00


In [ ]:
df["Make"].nunique()

4

In [46]:
df.nunique()

Make                 4
Model                5
Year                 3
Engine HP            4
Engine Cylinders     2
Transmission Type    2
Vehicle_Style        4
MSRP                 5
dtype: int64

### Missing Values

In [47]:
df.isnull()

,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Vehicle_Style,MSRP
0,False,False,False,False,False,False,False,False
1,False,False,False,True,False,False,False,False
2,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False


In [48]:
df.isnull().sum()

Make                 0
Model                0
Year                 0
Engine HP            1
Engine Cylinders     0
Transmission Type    0
Vehicle_Style        0
MSRP                 0
dtype: int64

### Grouping

In [ ]:
df.groupby("Transmission Type")["MSRP"].mean()

Transmission Type
AUTOMATIC    30800.000000
MANUAL       29776.666667
Name: MSRP, dtype: float64

### Getting the NumPy Arrays

In [ ]:
df["MSRP"].values

array([ 2000, 27150, 54990, 34450, 32340])

In [ ]:
df.to_dict(orient="records")

[{'Make': 'Nissan',
  'Model': 'Stanza',
  'Year': 1991,
  'Engine HP': 138.0,
  'Engine Cylinders': 4,
  'Transmission Type': 'MANUAL',
  'Vehicle_Style': 'sedan',
  'MSRP': 2000},
 {'Make': 'Hyundai',
  'Model': 'Sonata',
  'Year': 2017,
  'Engine HP': nan,
  'Engine Cylinders': 4,
  'Transmission Type': 'AUTOMATIC',
  'Vehicle_Style': 'sedan',
  'MSRP': 27150},
 {'Make': 'Lotus',
  'Model': 'Elise',
  'Year': 2010,
  'Engine HP': 218.0,
  'Engine Cylinders': 4,
  'Transmission Type': 'MANUAL',
  'Vehicle_Style': 'convertible',
  'MSRP': 54990},
 {'Make': 'GMC',
  'Model': 'Acadia',
  'Year': 2017,
  'Engine HP': 194.0,
  'Engine Cylinders': 4,
  'Transmission Type': 'AUTOMATIC',
  'Vehicle_Style': '4dr_suv',
  'MSRP': 34450},
 {'Make': 'Nissan',
  'Model': 'Frontier',
  'Year': 2017,
  'Engine HP': 261.0,
  'Engine Cylinders': 6,
  'Transmission Type': 'MANUAL',
  'Vehicle_Style': 'pickup',
  'MSRP': 32340}]