In [2]:
# Free RAM
!free -h

               total        used        free      shared  buff/cache   available
Mem:            15Gi       8.1Gi       1.2Gi       212Mi       7.7Gi       7.5Gi
Swap:           19Gi       147Mi        19Gi


In [3]:
# Free CPU
!lscpu

Architecture:                x86_64
  CPU op-mode(s):            32-bit, 64-bit
  Address sizes:             43 bits physical, 48 bits virtual
  Byte Order:                Little Endian
CPU(s):                      12
  On-line CPU(s) list:       0-11
Vendor ID:                   AuthenticAMD
  Model name:                AMD Ryzen 5 2600 Six-Core Processor
    CPU family:              23
    Model:                   8
    Thread(s) per core:      2
    Core(s) per socket:      6
    Socket(s):               1
    Stepping:                2
    Frequency boost:         enabled
    CPU(s) scaling MHz:      46%
    CPU max MHz:             3400.0000
    CPU min MHz:             1550.0000
    BogoMIPS:                6786.49
    Flags:                   fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pg
                             e mca cmov pat pse36 clflush mmx fxsr sse sse2 ht s
                             yscall nx mmxext fxsr_opt pdpe1gb rdtscp lm constan
                          

In [4]:
# Disk
!df -h

Filesystem      Size  Used Avail Use% Mounted on
tmpfs           1.6G  1.9M  1.6G   1% /run
efivarfs        128K  9.4K  114K   8% /sys/firmware/efi/efivars
/dev/sdb3       211G   49G  151G  25% /
tmpfs           7.8G   32M  7.8G   1% /dev/shm
tmpfs           5.0M     0  5.0M   0% /run/lock
/dev/sdb2       4.0G  3.4G  665M  84% /recovery
/dev/sdb1      1020M  438M  583M  43% /boot/efi
/dev/sdc2       932G  351G  581G  38% /mnt/HD2
/dev/sda2       932G  312G  621G  34% /mnt/HD1
tmpfs           1.6G  2.5M  1.6G   1% /run/user/1000


In [5]:
# GPU
!nvidia-smi

Tue Jun  9 16:19:17 2026       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 580.159.03             Driver Version: 580.159.03     CUDA Version: 13.0     |
+-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA GeForce GTX 1660 Ti     Off |   00000000:07:00.0  On |                  N/A |
|  0%   50C    P8              7W /  120W |    1872MiB /   6144MiB |      6%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

In [4]:
import pandas as pd

In [5]:
url = "https://raw.githubusercontent.com/alexeygrigorev/datasets/master/housing.csv"

df = pd.read_csv(url)

In [6]:
df.head()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,ocean_proximity
0,-122.23,37.88,41.0,880.0,129.0,322.0,126.0,8.3252,452600.0,NEAR BAY
1,-122.22,37.86,21.0,7099.0,1106.0,2401.0,1138.0,8.3014,358500.0,NEAR BAY
2,-122.24,37.85,52.0,1467.0,190.0,496.0,177.0,7.2574,352100.0,NEAR BAY
3,-122.25,37.85,52.0,1274.0,235.0,558.0,219.0,5.6431,341300.0,NEAR BAY
4,-122.25,37.85,52.0,1627.0,280.0,565.0,259.0,3.8462,342200.0,NEAR BAY


# **Introduction to NumPy**
- Create arrays
- Multi-dimensional arrays
- Random arrays
- Element-wise operations
- Summarizing operations

In [7]:
import numpy as np

In [8]:
np

<module 'numpy' from '/mnt/HD2/Data_Science/ml-engineering-zoomcamp/.venv/lib/python3.12/site-packages/numpy/__init__.py'>

## Creating Arrays

In [9]:
# Creates an array of zeros.
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [10]:
# Creates an array of ones
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [11]:
# Creates an array filled with arbitrary numbers
np.full(10, 2.5) # size and element we want to fill with.

array([2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5])

In [13]:
# Convert a list into an array
a = np.array([1, 2, 3, 4, 5])

In [14]:
a

array([1, 2, 3, 4, 5])

In [15]:
a[2] # Accessing an element

np.int64(3)

In [16]:
# Changing an element of the array
a[2] = 200

In [17]:
a

array([  1,   2, 200,   4,   5])

In [18]:
# Creates an array from a specific range
np.arange(10) # Array from zero to nine

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
np.arange(3, 10) # Array from 3 to 9

array([3, 4, 5, 6, 7, 8, 9])

In [20]:
# Creates an array filled with number between the values specified in the arguments
np.linspace(0, 1) # By default, creates an array of size 50.

array([0.        , 0.02040816, 0.04081633, 0.06122449, 0.08163265,
       0.10204082, 0.12244898, 0.14285714, 0.16326531, 0.18367347,
       0.20408163, 0.2244898 , 0.24489796, 0.26530612, 0.28571429,
       0.30612245, 0.32653061, 0.34693878, 0.36734694, 0.3877551 ,
       0.40816327, 0.42857143, 0.44897959, 0.46938776, 0.48979592,
       0.51020408, 0.53061224, 0.55102041, 0.57142857, 0.59183673,
       0.6122449 , 0.63265306, 0.65306122, 0.67346939, 0.69387755,
       0.71428571, 0.73469388, 0.75510204, 0.7755102 , 0.79591837,
       0.81632653, 0.83673469, 0.85714286, 0.87755102, 0.89795918,
       0.91836735, 0.93877551, 0.95918367, 0.97959184, 1.        ])

In [21]:
np.linspace(0, 1, 10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

## Multi-dimensional arrays

In [22]:
np.zeros((5, 2)) # Rows, columns

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [24]:
n = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

In [27]:
n[0] # access the first row

array([1, 2, 3])

In [28]:
n[0][1] # access first row, second column.

np.int64(2)

In [29]:
# Similarly
n[0, 1]

np.int64(2)

In [30]:
# Re-writing the entire row
n[2] = [0, 0, 0]

In [31]:
n

array([[1, 2, 3],
       [4, 5, 6],
       [0, 0, 0]])

In [34]:
# Access only the column
n[:,1]

array([2, 5, 0])

## Random arrays

In [39]:
# Generates a random array with 5 rows and 2 columns that follows a uniform distribution ranging from 0 to 1.
a = np.random.rand(5,2)
a

array([[0.44375805, 0.2968221 ],
       [0.05408037, 0.75285609],
       [0.7156307 , 0.49439086],
       [0.17885523, 0.44178681],
       [0.89724099, 0.75250797]])

In [41]:
# Generates a random array from the standard normal distribution
b = np.random.randn(5,2)
b

array([[-0.91429708, -0.69284732],
       [-0.89343031,  1.28784133],
       [ 0.87009278, -0.21525428],
       [ 0.44917737, -0.44534774],
       [ 1.32851005, -0.76134727]])

In [45]:
# Generates a random array with integer values
c = np.random.randint(low=0, high=100, size=[10, 3])
c

array([[22, 45,  5],
       [89, 31, 96],
       [ 3, 20, 78],
       [25,  8, 91],
       [ 4, 49, 60],
       [19,  8, 59],
       [77, 26, 98],
       [88, 41, 87],
       [39, 56, 89],
       [17, 18, 91]])

## Element-wise operations

In [46]:
n = np.arange(5)
n

array([0, 1, 2, 3, 4])

In [47]:
# Add the value of the scalar to each element inside the array
n + 1

array([1, 2, 3, 4, 5])

In [48]:
# Multiply all the entries by a scalar
n * 2

array([0, 2, 4, 6, 8])

In [49]:
n / 100

array([0.  , 0.01, 0.02, 0.03, 0.04])

In [57]:
# Chain of operations
(10 + (n * 2)) ** 2 / 100

array([1.  , 1.44, 1.96, 2.56, 3.24])

In [56]:
b = (10 + (n * 2)) ** 2 / 100

In [58]:
# Combine two arrays
c = n + b
c

array([1.  , 2.44, 3.96, 5.56, 7.24])

## Comparison Operations

In [60]:
# Element-wise comparison
n >= 2

array([False, False,  True,  True,  True])

In [61]:
n > b

array([False, False,  True,  True,  True])

In [62]:
n

array([0, 1, 2, 3, 4])

In [63]:
b

array([1.  , 1.44, 1.96, 2.56, 3.24])

In [67]:
# Analyse which element of an array is greater then the other array
n[n > b] # Returns the elements of A that has truthiness

array([2, 3, 4])

## Summarizing operations
Instead of return another array, it returns a single number

In [68]:
a

array([[0.44375805, 0.2968221 ],
       [0.05408037, 0.75285609],
       [0.7156307 , 0.49439086],
       [0.17885523, 0.44178681],
       [0.89724099, 0.75250797]])

In [69]:
a.sum()

np.float64(5.027929168700592)

In [70]:
a.mean()

np.float64(0.5027929168700591)

In [71]:
a.max()

np.float64(0.8972409912970633)

In [72]:
a.min()

np.float64(0.05408037498132423)

In [74]:
np.mean(a, axis=0) # Mean of each column

array([0.45791307, 0.54767276])

In [75]:
np.mean(a, axis=1) # Mean of each row

array([0.37029007, 0.40346823, 0.60501078, 0.31032102, 0.82487448])

# **Linear Algebra Refresher**
- Vector Operations
- Multiplication
- Matrix Inverse

## Vector Operations

In [78]:
a = np.array([2, 4, 5, 6])
a

array([2, 4, 5, 6])

In [79]:
2 * a

array([ 4,  8, 10, 12])

In this operation above, we are just multiplying the vector "a" by a scalar of 2. In Linear Algebra, this mean to multiply each entry of the vector by this scalar.

In [80]:
b = np.array([1, 0, 0, 2])

In [81]:
a + b

array([3, 4, 5, 8])

In the operation above, we are adding the vector "a" with the vector "b". It just mean that we area adding element-wise the vector values of "a" with the vector values of "b".

## Multiplication
- Vector-vector multiplication (**dot product**)
- Matrix-vector multiplication
- Matrix-matrix multiplication

In [82]:
a

array([2, 4, 5, 6])

In [83]:
b

array([1, 0, 0, 2])

The dot product is not just a element-wise multiplication. It is a element-wise multiplication followed by a sum. The result generates a single number.

In [86]:
# Implementation of a function that calculates the dot product
def dot_product(u: np.array, v: np.array) -> int:
    assert u.shape[0] == v.shape[0]
    n = u.shape[0]
    result = 0.0
    for i in range(n):
        result = result + u[i] * v[i]

    return result

In [87]:
dot_product(a, b)

np.float64(14.0)

In [88]:
# NumPy has a implemented function that does this calculation
a.dot(b)

np.int64(14)